export const HOME_WIDGET_SIZE_CLASS_MAP = Object.freeze({
  '1x1': 'col-span-1 row-span-1',
  '2x1': 'col-span-2 row-span-1',
  '2x2': 'col-span-2 row-span-2',
  '4x1': 'col-span-4 row-span-1',
  '4x2': 'col-span-4 row-span-2',
  '4x3': 'col-span-4 row-span-3',
  '4x4': 'col-span-4 row-span-4',
})

export const BUILT_IN_HOME_WIDGETS = Object.freeze([
  {
    id: 'weather',
    variant: 'weather',
    size: '2x2',
    icon: 'fas fa-cloud-sun',
    preview: 'weather',
    family: 'spectrum',
    interaction: 'toggle_weather_details',
    nameZh: '天气',
    nameEn: 'Weather',
  },
  {
    id: 'calendar',
    variant: 'calendar',
    size: '2x2',
    icon: 'fas fa-calendar-days',
    preview: 'calendar',
    family: 'spectrum',
    interaction: 'open_calendar',
    nameZh: '日历',
    nameEn: 'Calendar',
  },
  {
    id: 'music',
    variant: 'music',
    size: '4x2',
    icon: 'fas fa-music',
    preview: 'music',
    family: 'paper',
    interaction: 'music_controls',
    nameZh: '音乐',
    nameEn: 'Music',
  },
  {
    id: 'system',
    variant: 'system',
    size: '2x2',
    icon: 'fas fa-sliders',
    preview: 'system',
    nameZh: '系统状态',
    nameEn: 'System Status',
  },
  {
    id: 'breath_halo',
    variant: 'breath_halo',
    size: '2x2',
    icon: 'fas fa-circle-dot',
    preview: 'breath-halo',
    family: 'spectrum',
    interaction: 'cycle_breath',
    nameZh: '潮汐呼吸',
    nameEn: 'Tidal Breath',
  },
  {
    id: 'quick_heart',
    variant: 'heart',
    size: '1x1',
    icon: 'fas fa-heart',
    preview: 'heart',
    nameZh: '快捷爱心',
    nameEn: 'Quick Heart',
  },
  {
    id: 'quick_disc',
    variant: 'disc',
    size: '1x1',
    icon: 'fas fa-compact-disc',
    preview: 'disc',
    nameZh: '快捷唱片',
    nameEn: 'Quick Disc',
  },
  {
    id: 'focus_pulse',
    variant: 'focus_pulse',
    size: '1x1',
    icon: 'fas fa-bullseye',
    preview: 'focus-pulse',
    family: 'pocket',
    interaction: 'focus_timer',
    nameZh: '珐琅专注环',
    nameEn: 'Enamel Focus',
  },
  {
    id: 'daily_steps',
    variant: 'daily_steps',
    size: '2x1',
    icon: 'fas fa-shoe-prints',
    preview: 'daily-steps',
    nameZh: '今日步数',
    nameEn: 'Daily Steps',
  },
  {
    id: 'photo_note',
    variant: 'photo_note',
    size: '2x2',
    icon: 'fas fa-note-sticky',
    preview: 'photo-note',
    family: 'pocket',
    interaction: 'mood_window',
    nameZh: '心情百叶窗',
    nameEn: 'Mood Window',
  },
  {
    id: 'commute_strip',
    variant: 'commute_strip',
    size: '4x1',
    icon: 'fas fa-train-subway',
    preview: 'commute-strip',
    family: 'pocket',
    interaction: 'open_map',
    nameZh: '通勤轨道',
    nameEn: 'Commute Rail',
  },
  {
    id: 'today_agenda',
    variant: 'today_agenda',
    size: '4x2',
    icon: 'fas fa-list-check',
    preview: 'today-agenda',
    family: 'paper',
    interaction: 'open_calendar',
    nameZh: '今日日程',
    nameEn: 'Today Agenda',
  },
  {
    id: 'week_rhythm',
    variant: 'week_rhythm',
    size: '4x3',
    icon: 'fas fa-chart-simple',
    preview: 'week-rhythm',
    family: 'paper',
    interaction: 'cycle_day',
    nameZh: '纸上月相',
    nameEn: 'Paper Moon Week',
  },
  {
    id: 'memory_board',
    variant: 'memory_board',
    size: '4x4',
    icon: 'fas fa-images',
    preview: 'memory-board',
    family: 'paper',
    interaction: 'select_photos',
    nameZh: '彩色记忆墙',
    nameEn: 'Color Memory Wall',
  },
  {
    id: 'music_wave',
    variant: 'music_wave',
    size: '4x1',
    icon: 'fas fa-wave-square',
    preview: 'music-wave',
    family: 'spectrum',
    interaction: 'music_controls',
    nameZh: '流光声纹',
    nameEn: 'Aurora Waveform',
  },
  {
    id: 'ambient_scene',
    variant: 'ambient_scene',
    size: '4x4',
    icon: 'fas fa-moon',
    preview: 'ambient-scene',
    family: 'spectrum',
    interaction: 'toggle_scene',
    nameZh: '昼夜流光',
    nameEn: 'Day & Night Veil',
  },
  {
    id: 'world_pulse',
    variant: 'world_pulse',
    size: '4x3',
    icon: 'fas fa-earth-asia',
    preview: 'world-pulse',
    family: 'editorial',
    interaction: 'open_world_hub',
    nameZh: '世界脉冲',
    nameEn: 'World Pulse',
  },
])

export const BUILT_IN_HOME_WIDGET_IDS = Object.freeze(
  BUILT_IN_HOME_WIDGETS.map((widget) => widget.id),
)

export const BUILT_IN_HOME_WIDGET_BY_ID = Object.freeze(
  Object.fromEntries(BUILT_IN_HOME_WIDGETS.map((widget) => [widget.id, widget])),
)

export const BUILT_IN_HOME_WIDGET_BY_VARIANT = Object.freeze(
  Object.fromEntries(BUILT_IN_HOME_WIDGETS.map((widget) => [widget.variant, widget])),
)

export const HOME_WIDGET_REGISTRY_ENTRIES = Object.freeze(
  Object.fromEntries(
    BUILT_IN_HOME_WIDGETS.map((widget) => [
      widget.id,
      Object.freeze({
        id: widget.id,
        kind: 'widget',
        variant: widget.variant,
        size: widget.size,
        family: widget.family || 'system',
        interaction: widget.interaction || '',
        span: HOME_WIDGET_SIZE_CLASS_MAP[widget.size],
      }),
    ]),
  ),
)
