import { describe, expect, test } from 'vitest'
import {
  hasChatAiSocialEvents,
  normalizeChatAiSocialEvents,
} from '../src/lib/chat-ai-social-proposals'

describe('chat AI social proposal normalization', () => {
  test('keeps supported role-side social proposals', () => {
    expect(
      normalizeChatAiSocialEvents({
        socialEvents: [
          { type: 'role_greeting_request', explanation: 'open contact' },
          { eventType: 'role_block_user', reason: 'conflict escalated' },
        ],
      }),
    ).toEqual([
      { eventType: 'role_greeting_request', explanation: 'open contact' },
      { eventType: 'role_block_user', explanation: 'conflict escalated' },
    ])
  })

  test('accepts compatible payload keys and ignores unsupported proposals', () => {
    expect(
      normalizeChatAiSocialEvents({
        social_events: [
          null,
          {},
          { type: 'user_block_role', explanation: 'not generated by role' },
          { type: 'role_unblock_user', explanation: 'restored' },
        ],
      }),
    ).toEqual([{ eventType: 'role_unblock_user', explanation: 'restored' }])
  })

  test('trims text and caps proposal count', () => {
    const events = Array.from({ length: 8 }, () => ({
      type: 'role_refuse_messages',
      explanation: ` ${'x'.repeat(260)} `,
    }))

    const normalized = normalizeChatAiSocialEvents({ chatSocialEvents: events })

    expect(normalized).toHaveLength(5)
    expect(normalized[0].explanation).toHaveLength(220)
    expect(hasChatAiSocialEvents({ chatSocialEvents: events })).toBe(true)
    expect(hasChatAiSocialEvents({ socialEvents: [{ type: 'unknown' }] })).toBe(false)
  })
})
