import { computed, reactive } from 'vue'
import { CAREER_STORAGE_KEY, CAREER_STORAGE_VERSION, getCareerListing } from '../lib/career-shell-data'
const TABS=new Set(['discover','saved','applications','profile']);const defaults=()=>({version:CAREER_STORAGE_VERSION,activeTab:'discover',savedListingIds:[],applicationDrafts:[],profileDraft:{headline:'',skills:[]}})
const cleanIds=(v)=>[...new Set((Array.isArray(v)?v:[]).filter(getCareerListing))]
const cleanDraft=(d)=>{const l=getCareerListing(d?.listingId);if(!l||l.status!=='open')return null;return{listingId:l.id,materialNote:String(d?.materialNote||'').slice(0,300)}}
export const normalizeCareerState=(c)=>{const b=defaults();if(!c||c.version!==CAREER_STORAGE_VERSION)return b;const drafts=(Array.isArray(c.applicationDrafts)?c.applicationDrafts:[]).map(cleanDraft).filter(Boolean);return{version:CAREER_STORAGE_VERSION,activeTab:TABS.has(c.activeTab)?c.activeTab:'discover',savedListingIds:cleanIds(c.savedListingIds),applicationDrafts:drafts.filter((d,i)=>drafts.findIndex(x=>x.listingId===d.listingId)===i).slice(0,12),profileDraft:{headline:String(c.profileDraft?.headline||'').slice(0,100),skills:[...new Set((Array.isArray(c.profileDraft?.skills)?c.profileDraft.skills:[]).map(x=>String(x).slice(0,30)).filter(Boolean))].slice(0,8)}}}
const load=()=>{try{const raw=window.localStorage?.getItem(CAREER_STORAGE_KEY);return raw?normalizeCareerState(JSON.parse(raw)):defaults()}catch{return defaults()}};const state=reactive(load());const clone=()=>JSON.parse(JSON.stringify(state));const save=n=>{try{window.localStorage.setItem(CAREER_STORAGE_KEY,JSON.stringify(n));Object.assign(state,n);return{ok:true}}catch{return{ok:false,error:'write_failed'}}}
export const useCareerShellState=()=>({previewState:state,activeTab:computed(()=>state.activeTab),savedListingIds:computed(()=>state.savedListingIds),applicationDrafts:computed(()=>state.applicationDrafts),profileDraft:computed(()=>state.profileDraft),setActiveTab(tab){if(!TABS.has(tab))return{ok:false,error:'tab_invalid'};const n=clone();n.activeTab=tab;return save(n)},toggleSaved(id){if(!getCareerListing(id))return{ok:false,error:'listing_missing'};const n=clone();n.savedListingIds=n.savedListingIds.includes(id)?n.savedListingIds.filter(x=>x!==id):[...n.savedListingIds,id];return save(n)},saveApplicationDraft(d){const clean=cleanDraft(d);if(!clean)return{ok:false,error:'draft_invalid'};const n=clone();n.applicationDrafts=[clean,...n.applicationDrafts.filter(x=>x.listingId!==clean.listingId)];return save(n)},removeApplicationDraft(id){const n=clone();n.applicationDrafts=n.applicationDrafts.filter(x=>x.listingId!==id);return save(n)},updateProfile(patch){const n=normalizeCareerState({...clone(),profileDraft:{...state.profileDraft,...patch}});return save(n)}})
export const resetCareerShellStateForTesting=()=>{Object.assign(state,defaults());try{window.localStorage?.removeItem(CAREER_STORAGE_KEY)}catch{/*best effort*/}}
