import { computed, reactive } from 'vue'
import { PARCEL_STORAGE_KEY, PARCEL_STORAGE_VERSION, getParcelShipment } from '../lib/parcel-shell-data'
const TABS = new Set(['track', 'send', 'inbox', 'me'])
const defaults = () => ({ version: PARCEL_STORAGE_VERSION, activeTab: 'track', pinnedShipmentIds: [], sendDraft: { recipient: '', addressLabel: '', itemType: 'parcel', note: '' }, pickupReminderEnabled: true })
export const normalizeParcelState = (candidate) => { const base = defaults(); if (!candidate || candidate.version !== PARCEL_STORAGE_VERSION) return base; return { version: PARCEL_STORAGE_VERSION, activeTab: TABS.has(candidate.activeTab) ? candidate.activeTab : 'track', pinnedShipmentIds: [...new Set((Array.isArray(candidate.pinnedShipmentIds) ? candidate.pinnedShipmentIds : []).filter(getParcelShipment))], sendDraft: { recipient: String(candidate.sendDraft?.recipient || '').slice(0,80), addressLabel: String(candidate.sendDraft?.addressLabel || '').slice(0,100), itemType: ['parcel','document'].includes(candidate.sendDraft?.itemType) ? candidate.sendDraft.itemType : 'parcel', note: String(candidate.sendDraft?.note || '').slice(0,300) }, pickupReminderEnabled: candidate.pickupReminderEnabled !== false } }
const load = () => { try { const raw = window.localStorage?.getItem(PARCEL_STORAGE_KEY); return raw ? normalizeParcelState(JSON.parse(raw)) : defaults() } catch { return defaults() } }
const state = reactive(load()); const clone = () => JSON.parse(JSON.stringify(state)); const save = (next) => { try { window.localStorage.setItem(PARCEL_STORAGE_KEY, JSON.stringify(next)); Object.assign(state,next); return {ok:true} } catch { return {ok:false,error:'write_failed'} } }
export const useParcelShellState = () => ({ previewState: state, activeTab: computed(()=>state.activeTab), pinnedShipmentIds: computed(()=>state.pinnedShipmentIds), sendDraft: computed(()=>state.sendDraft), pickupReminderEnabled: computed(()=>state.pickupReminderEnabled), setActiveTab(tab){if(!TABS.has(tab))return{ok:false,error:'tab_invalid'};const n=clone();n.activeTab=tab;return save(n)}, togglePinned(id){if(!getParcelShipment(id))return{ok:false,error:'shipment_missing'};const n=clone();n.pinnedShipmentIds=n.pinnedShipmentIds.includes(id)?n.pinnedShipmentIds.filter(x=>x!==id):[...n.pinnedShipmentIds,id];return save(n)}, updateSendDraft(patch){const n=clone();n.sendDraft={...n.sendDraft,...patch};return save(normalizeParcelState(n))}, togglePickupReminder(){const n=clone();n.pickupReminderEnabled=!n.pickupReminderEnabled;return save(n)} })
export const resetParcelShellStateForTesting = () => { Object.assign(state,defaults()); try{window.localStorage?.removeItem(PARCEL_STORAGE_KEY)}catch{/* best effort */} }
